/* auto-generated by NAPI-RS */
/* eslint-disable */
/** This is the exported async function. napi will make it return a Promise in Node. */
export declare function handleRequest(method: string, path: string, headers?: Array<[string, string]> | undefined | null, body?: Buffer | undefined | null): Promise<string>
