/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function handleRequest(method: string, path: string, headers?: Array<[string, string]> | undefined | null, body?: Buffer | undefined | null): Promise<string>