name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run linting
        run: npm run lint
      - name: Build library
        run: npm run build
      - name: Install sample dependencies
        run: |
          cd sample
          npm ci
      - name: Build sample app
        run: |
          cd sample
          npm run build
      - name: Run sample tests
        run: |
          cd sample
          npm test

  e2e-test:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build library
        run: npm run build
      - name: Install sample dependencies
        run: |
          cd sample
          npm ci
      - name: Build sample app
        run: |
          cd sample
          npm run build
      - name: Run end-to-end tests
        run: |
          cd sample
          npm run test:e2e

  benchmark:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build library
        run: npm run build
      - name: Install sample dependencies
        run: |
          cd sample
          npm ci
      - name: Build sample app
        run: |
          cd sample
          npm run build
      - name: Run benchmarks
        run: npm run bench
